Origin : http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#   
Translator : Hongpu Liu

# 什么是PyTorch
PyTorch是基于Python的科学计算包，满足两类不同的需求：
- 可以利用强力GPU算力的NumPy替代者
- 提供灵活性与速度的深度学习研究平台

## 1. 开始
### 1.1 Tensors
Tensors与NumPy的**ndarrays**类似，但是额外增加了利用GPU来加速计算的功能。

In [1]:
from __future__ import print_function
import torch

创建一个未初始化的5x3的矩阵：

In [2]:
x = torch.Tensor(5, 3)
print(x)


1.00000e-12 *
  0.0000  0.0000  0.0127
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  2.3096  0.0000
  2.2665  0.0000  0.0000
[torch.FloatTensor of size 5x3]



创建一个随机初始化的矩阵：

In [3]:
x = torch.rand(5, 3)
print(x)


 0.8914  0.1685  0.7866
 0.1290  0.3920  0.5180
 0.8897  0.6440  0.0309
 0.4056  0.7855  0.7780
 0.7028  0.4068  0.6095
[torch.FloatTensor of size 5x3]



获得x的维度：

In [4]:
print(x.size())

torch.Size([5, 3])


>**注意：``torch.Size``实际上是一个元组，支持所有的元组操作。**

### 1.2 Operations
部分操作符有多种语法格式，首先看一下加法操作。

加法：格式1

In [5]:
y = torch.rand(5, 3)
print(x + y)


 1.8878  1.0236  1.5075
 0.4811  0.7521  1.4505
 1.1849  0.7474  0.2468
 1.2811  0.8920  1.6043
 1.0801  1.1520  0.6730
[torch.FloatTensor of size 5x3]



加法：格式2

In [6]:
print(torch.add(x, y))


 1.8878  1.0236  1.5075
 0.4811  0.7521  1.4505
 1.1849  0.7474  0.2468
 1.2811  0.8920  1.6043
 1.0801  1.1520  0.6730
[torch.FloatTensor of size 5x3]



加法：以输出tensor作为参数

In [7]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.8878  1.0236  1.5075
 0.4811  0.7521  1.4505
 1.1849  0.7474  0.2468
 1.2811  0.8920  1.6043
 1.0801  1.1520  0.6730
[torch.FloatTensor of size 5x3]



加法：替换值

In [8]:
# 将x加到y上
y.add_(x)
print(y)


 1.8878  1.0236  1.5075
 0.4811  0.7521  1.4505
 1.1849  0.7474  0.2468
 1.2811  0.8920  1.6043
 1.0801  1.1520  0.6730
[torch.FloatTensor of size 5x3]



>**注意：任何会改变一个Tensor的替换操作，后面都会有一个下划线``_``。例如：``x.copy_(y)``，``x.t_()``，会改变``x``。**

可以对Tensor使用标准的NumPy索引操作（此处应有掌声）。

In [9]:
print(x[:,1])


 0.1685
 0.3920
 0.6440
 0.7855
 0.4068
[torch.FloatTensor of size 5]



改变张量大小：如果需要改变张量的大小和形状，可以使用``torch.view``：

In [10]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1表示由其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


**后续阅读**
包括转置、索引、切片、数学运算、线性代数、随机采样等等100多种Tensor操作，请参阅[文档](http://pytorch.org/docs/master/torch.html)。

## 2. NumPy与Tensor
在``Torch Tensor``和``NumPy array``之间进行转换是轻而易举的事情。
``Torch Tensor``和``NumPy array``共享底层的内存区间，修改其中一个，另一个也会跟着变化。

### 2.1 将一个Torch Tensor转换为一个NumPy Array

In [11]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [12]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


执行下面的语句块可以看到NumPy Array的值是如何变化的。

In [13]:
a.add_(1) # 注意：此处进行加法运算的两个变量维度不一样，此时会自动进行广播（Broadcasting）
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


### 2.2 将NumPy Array转换为Torch Tensor
下面的语句块展示了当改变Numpy Array时，对应的Torch Tensor是如何自动改变的。

In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



除了``CharTensor``之外，所有CPU上运行的Tensors都支持与NumPy之间的转换。

## 3. CUDA Tensors
Tensors可以通过``.cuda``方法，移动到GPU上。

In [15]:
# 如果CUDA可用，则在GPU上运行
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y